###
# About/contact for the site author
#
# name of the author of the site
name = "William Droz"
# description to display in the sidebar
description = "I’ve been programming since 2004 and I got my master degree in software engineering in 2015. I worked as a research assistant at “He-arc Ingénierie” until 2018. I'm now working as a Research and Development Engineer at Idiap. With my work, I have the opportunity to play with cutting edge technologies."

# the profile image of the author to display in the sidebar
gravatar = "28db695016ffa369ce54f28f792ac3a5" # md5 hash of your email address # sidebar.html

# contact links to reach the author
#  - `name` is the font-awesome char name
#  - `path` is the link to follow 
contact = [
  { name = "linkedin", path = "https://www.linkedin.com/in/william-droz-13107673" },
  { name = "github", path = "https://github.com/wdroz" },
  { name = "email", path = "mailto:william.droz.ch@gmail.com" }
]
