# The URL the site will be built for
base_url = "https://william-droz.com"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "codinfox-zola"

title = "William Droz - Blog"
description = "I talk about cool technologies I play with"

# The default language; used in feeds.
default_language = "en"

taxonomies = [
  {name = "tags", lang = "en"},
  {name = "categories", feed = true, lang = "en"},
]


[extra]
# Put all your custom variables here
logo = "/mylogo_2.png"

version = "1.0.1"
copyrightyear = "2020"

# Puglins
mathjax = true # whether support mathjax
google_analytics_token = "" # a UA-00000000-1 like code or leave blank if you don't want google analytics
disqus_short_name = "william-droz.com" # leave blank if you don't want disqus

# Where are tags and categories displayed
tag_page = "/tags/"
category_page = "/categories/"

# hero
image = "/img/linux.jpg"  # image for the home page
caption = "Funny meme from Reddit"  # caption for the home page image
#

# show or not the reading time based on https://help.medium.com/hc/en-us/articles/214991667-Read-time
read_time = true